// Code generated by "stringer -type=DeviceFunction -linecomment"; DO NOT EDIT.

package topology

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Fake-0]
	_ = x[OOBServer-1]
	_ = x[OOBSwitch-2]
	_ = x[Exit-3]
	_ = x[SuperSpine-4]
	_ = x[Spine-5]
	_ = x[Leaf-6]
	_ = x[TOR-7]
	_ = x[Host-8]
	_ = x[NoFunction-9]
}

const _DeviceFunction_name = "fakeoob-serveroob-switchexitsuperspinespineleaftorhostNoFunction"

var _DeviceFunction_index = [...]uint8{0, 4, 14, 24, 28, 38, 43, 47, 50, 54, 64}

func (i DeviceFunction) String() string {
	if i < 0 || i >= DeviceFunction(len(_DeviceFunction_index)-1) {
		return "DeviceFunction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceFunction_name[_DeviceFunction_index[i]:_DeviceFunction_index[i+1]]
}
