// Code generated by "stringer -type=DeviceFunction -linecomment"; DO NOT EDIT.

package topology

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FunctionFake-0]
	_ = x[FunctionOOBServer-1]
	_ = x[FunctionOOBSwitch-2]
	_ = x[FunctionExit-3]
	_ = x[FunctionSuperSpine-4]
	_ = x[FunctionSpine-5]
	_ = x[FunctionLeaf-6]
	_ = x[FunctionTOR-7]
	_ = x[FunctionHost-8]
	_ = x[NoFunction-9]
}

const _DeviceFunction_name = "fakeoob-serveroob-switchexitsuperspinespineleaftorhostNoFunction"

var _DeviceFunction_index = [...]uint8{0, 4, 14, 24, 28, 38, 43, 47, 50, 54, 64}

func (i DeviceFunction) String() string {
	if i < 0 || i >= DeviceFunction(len(_DeviceFunction_index)-1) {
		return "DeviceFunction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceFunction_name[_DeviceFunction_index[i]:_DeviceFunction_index[i+1]]
}
