on: [push, pull_request]
name: Run tests
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04]
        # We require go1.16 for go:embed support.
        # TODO: figure out how to use gotip
        go-version: [1.16.x]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install libvirt and xmllint
      run: |
        sudo apt-get update && sudo apt-get install -y \
          libvirt-dev libxml2-utils
    - name: Install libvirt-clients (ubuntu-latest)
      run: sudo apt-get install -y libvirt-clients
      if: matrix.os == 'ubuntu-latest'
    - name: Install libvirt-bin (ubuntu-16.04)
      run: sudo apt-get install -y libvirt-bin
      if: matrix.os == 'ubuntu-16.04'
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test
